In [4]:
#Author; William Carey
#Student Id: C16315253
#Assignment 1

#import libraries
import pandas as pd
import csv

#create the keys that describe the features we are using to index
ContIndexes = ["age","fnlwgt","education-num","capital-gain","capital-loss","hours-per-week"]
CatIndexes = ["workclass","education","martial-status","occupation","relationship","race","sex","native-country","target"]

#create the writers to the files that we are working with
ConCSVFile = open("AssignmentDocs//C16315253Cont.csv","w",newline = "")
ConCSVWriter = csv.writer(ConCSVFile,delimiter = ',')
CatCSVFile = open("AssignmentDocs//C16315253Cat.csv","w",newline = "")
CatCSVWriter = csv.writer(CatCSVFile,delimiter = ',')

#Create the two headers to store our data
StandardColumnNames = ["FeatureName","Count","% Miss", "Card"]
ContinCSVFileHeaders = StandardColumnNames + ["Min","1st Qrt","Mean","Median","3rd Qrt","Max", "Std Dev"]
CatCSVFileHeaders = StandardColumnNames + ["Mode","Mode Freq","Mode %","2nd Mode","2nd Mode Freq","2nd Mode %"]

#reading and parsing the columns headers from the text file
columnsName = open(".//Data//feature_names.txt")
text_reader = columnsName.read()
dataFrame = pd.read_csv(".//Data//dataset.txt", header = None, na_values = ["?", " ?", "? "])
dataFrame.columns = text_reader.split("\n")

#dataFrame.head()

#writing the headers to the files before we proceed to gather the data
ConCSVWriter.writerow(ContinCSVFileHeaders)
CatCSVWriter.writerow(CatCSVFileHeaders)

#filter out the features of the application for both categorical and continous
for key in dataFrame.columns:
    #variables for calculation purpose
    calulationCount = dataFrame[key].count()
    MissingCount = dataFrame[key].isnull().sum()
    Cardinal = dataFrame[key].unique()
    
    #variables for writing to csv file
    FeatureName = str(key)
    FeatureCount = str(calulationCount)
    FeatureMissingCount = str("%.2f" % ((MissingCount / calulationCount) * 100))
    CardinalFeature = str(Cardinal)
    
    if(key in CatIndexes):
        #getting the dict together
        FeatureDict = dict(dataFrame[key].value_counts())
        ModeNoCount = 0
        #variable to work with the first mode
        FirstModeElement = ""
        FirstModeCount = 0
        FirstModeFrequency = 0
        
        #second mode variables
        SecondModeElement = ""
        SecondModeCount = 0
        SecondModeFrequency = 0
        
        ModeDict = {}
        #iterate over dictionary to get the first two modes
        for DictKey in FeatureDict:
            ModeCount = FeatureDict[DictKey]
            if(ModeNoCount == 0):
                FirstModeElement = DictKey
                FirstModeCount = FeatureDict[DictKey]
                FirstModeFrequency = (int(ModeCount) / calulationCount) * 100 
            
            if(ModeNoCount == 1):
                SecondModeElement = DictKey
                SecondModeCount = FeatureDict[DictKey]
                SecondModeFrequency = (int(ModeCount) / calulationCount) * 100 
            
            ModeNoCount = ModeNoCount + 1
            if(ModeNoCount == 2):
                break
        #end inner for loop
    
        CatDataCollection = [FeatureName,FeatureCount,FeatureMissingCount,CardinalFeature
                         str(FirstModeElement),str(FirstModeCount),
                         str("%.2f" % FirstModeFrequency), str(SecondModeElement),
                         str(SecondModeCount),str("%.2f" % SecondModeFrequency)]
        
        #writing the data to the file
        CatCSVWriter.writerow(CatDataCollection)
    #end collecting the category data
    
    #Now collecting the contin data features
    if(key in ContIndexes):
        Min = dataFrame[key].min()
        Max = dataFrame[key].max()
        Median = dataFrame[key].median()
        Mean = dataFrame[key].mean()
        FirstQrt = dataFrame[key].quantile(.25)
        ThirdQrt = dataFrame[key].quantile(.75)
        Std = dataFrame[key].std()
        
        ContDataCollection = [FeatureName,FeatureCount,FeatureMissingCount,CardinalFeature
            str(Min),str(FirstQrt),str("%.2f" % Mean), str(Median),str(ThirdQrt),str(max),
                              str("%.2f" % Std)]
        #writng the data to the contin
        ConCSVWriter.writerow(ContDataCollection)
    #end collecting the contin data
        
#end outer for loop

#close the files after writing 
ConCSVFile.close()
CatCSVFile.close()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,tr1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,tr2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,tr3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,tr4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,tr5,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [15]:
#checking for potential missing data
for Key in dataFrame.columns:
    print(dataFrame[Key].isnull().sum())
    print((dataFrame[Key].isnull().sum() / dataFrame[Key].count()) * 100)
    print("\n ")

0
0.0


0
0.0


1735
5.940763567882212


0
0.0


0
0.0


0
0.0


0
0.0


1742
5.966162065894924


0
0.0


0
0.0


0
0.0


0
0.0


0
0.0


0
0.0


554
1.8232080563417363


0
0.0

In [9]:
#checking for the cardinlity
for Key in dataFrame.columns:
    uniqueElements = dataFrame[Key].unique()
    print(len(uniqueElements))

30940
72
9
20880
16
16
7
15
6
5
2
119
91
93
42
2

In [7]:
dataFrame.age.value_counts().head()

36    849
35    844
23    841
31    840
34    840
Name: age, dtype: int64

In [14]:
#Convert to dict so we can access the mode and second mode
MyDict = dict(dataFrame.age.value_counts())

#MyDict
NumCount = 0

for key in MyDict:
    print(key)
    print(MyDict[key])
    
    HowMany = int(MyDict[key])
    
    Percentage = HowMany / dataFrame.age.count()
    
    print(Percentage * 100)
    NumCount = NumCount + 1
    
    if(NumCount == 2):
        break

36
849
2.744020685197156
35
844
2.7278603749191985

In [17]:
MyDict

{36: 849,
 35: 844,
 23: 841,
 31: 840,
 34: 840,
 33: 832,
 28: 824,
 37: 818,
 30: 812,
 25: 807,
 27: 801,
 38: 789,
 29: 780,
 32: 778,
 39: 773,
 41: 758,
 24: 756,
 40: 754,
 26: 747,
 42: 737,
 43: 736,
 22: 729,
 46: 702,
 20: 701,
 45: 699,
 44: 697,
 21: 691,
 19: 678,
 47: 672,
 50: 571,
 51: 558,
 49: 542,
 18: 524,
 48: 514,
 52: 449,
 53: 444,
 54: 397,
 55: 395,
 17: 381,
 58: 352,
 56: 351,
 57: 338,
 59: 334,
 60: 295,
 61: 281,
 62: 244,
 63: 217,
 64: 196,
 65: 170,
 67: 145,
 66: 145,
 68: 114,
 69: 103,
 70: 83,
 71: 68,
 72: 64,
 73: 60,
 74: 50,
 76: 45,
 75: 43,
 90: 41,
 77: 25,
 79: 22,
 81: 20,
 80: 20,
 78: 19,
 82: 12,
 84: 10,
 83: 6,
 88: 3,
 85: 3,
 87: 1}